CREATE ROLE authenticated;
CREATE ROLE service_role;
CREATE ROLE anon;
CREATE SCHEMA auth;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
GRANT USAGE ON SCHEMA auth, public TO authenticated;
CREATE TABLE public.servers(id uuid PRIMARY KEY);
CREATE TABLE public.test_members(server_id uuid, user_id uuid, manager boolean);
CREATE FUNCTION public.is_server_member(s uuid,u uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM test_members WHERE server_id=s AND user_id=u) $$;
CREATE FUNCTION public.has_server_permission(s uuid,u uuid,p text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT p='manage_channels' AND EXISTS(SELECT 1 FROM test_members WHERE server_id=s AND user_id=u AND manager) $$;
CREATE TABLE public.channels(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), server_id uuid NOT NULL REFERENCES public.servers(id),name text,position integer DEFAULT 0);
ALTER TABLE public.channels ENABLE ROW LEVEL SECURITY;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.channels TO authenticated;
CREATE POLICY channels_read ON public.channels FOR SELECT TO authenticated USING(public.is_server_member(server_id,auth.uid()));
CREATE POLICY channels_insert_admins ON public.channels FOR INSERT TO authenticated WITH CHECK(false);
CREATE POLICY channels_update_admins ON public.channels FOR UPDATE TO authenticated USING(false);
CREATE POLICY channels_delete_admins ON public.channels FOR DELETE TO authenticated USING(false);
CREATE PUBLICATION supabase_realtime;
INSERT INTO public.servers VALUES ('00000000-0000-0000-0000-000000000001'),('00000000-0000-0000-0000-000000000002');
INSERT INTO public.test_members VALUES ('00000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000010',true),('00000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000011',false);
