BEGIN;
CREATE ROLE authenticated;
CREATE SCHEMA auth;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
CREATE FUNCTION test_id(n int) RETURNS uuid LANGUAGE sql IMMUTABLE AS $$ SELECT lpad(n::text,32,'0')::uuid $$;
GRANT USAGE ON SCHEMA auth,public TO authenticated;
CREATE TABLE profiles(id uuid PRIMARY KEY);
CREATE TABLE servers(id uuid PRIMARY KEY,owner_id uuid);
CREATE TABLE channels(id uuid PRIMARY KEY,server_id uuid,type text);
CREATE TABLE server_members(id uuid PRIMARY KEY,server_id uuid,user_id uuid);
CREATE TABLE roles(id uuid PRIMARY KEY,server_id uuid,name text,color text,position int,permissions jsonb);
CREATE TABLE member_roles(member_id uuid,role_id uuid);
CREATE TABLE voice_move_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),recipient_id uuid,actor_id uuid,server_id uuid,source_channel_id uuid,destination_channel_id uuid NOT NULL,voice_session_id text,created_at timestamptz DEFAULT now());
CREATE PUBLICATION supabase_realtime;
CREATE FUNCTION is_server_owner(s uuid,u uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM servers WHERE id=s AND owner_id=u) $$;
CREATE FUNCTION member_server_id(m uuid) RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT server_id FROM server_members WHERE id=m $$;
CREATE FUNCTION has_server_permission(s uuid,u uuid,p text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT is_server_owner(s,u) OR EXISTS(SELECT 1 FROM server_members m JOIN member_roles mr ON mr.member_id=m.id JOIN roles r ON r.id=mr.role_id WHERE m.server_id=s AND m.user_id=u AND (coalesce((r.permissions->>'administrator')::boolean,false) OR coalesce((r.permissions->>p)::boolean,false))) $$;
CREATE FUNCTION has_channel_permission(c uuid,u uuid,p text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM channels JOIN server_members m ON m.server_id=channels.server_id WHERE channels.id=c AND m.user_id=u) $$;
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY roles_select ON roles FOR SELECT TO authenticated USING(true);
CREATE POLICY roles_update_admins ON roles FOR UPDATE TO authenticated USING(name<>'OWNER');
CREATE POLICY roles_delete_admins ON roles FOR DELETE TO authenticated USING(name<>'OWNER');
CREATE POLICY member_roles_insert_admins ON member_roles FOR INSERT TO authenticated WITH CHECK(true);
CREATE POLICY member_roles_delete_admins ON member_roles FOR DELETE TO authenticated USING(true);
GRANT SELECT,UPDATE,DELETE ON roles TO authenticated;
GRANT SELECT ON server_members TO authenticated;
INSERT INTO profiles SELECT test_id(n) FROM generate_series(1,5) n;
INSERT INTO servers VALUES(test_id(10),test_id(1)),(test_id(11),test_id(5));
INSERT INTO channels VALUES(test_id(20),test_id(10),'voice'),(test_id(21),test_id(10),'voice'),(test_id(22),test_id(11),'voice');
INSERT INTO server_members SELECT test_id(30+n),test_id(10),test_id(n) FROM generate_series(1,4) n;
INSERT INTO roles VALUES(test_id(41),test_id(10),'OWNER','#22d3ee',100,'{"administrator":true}'),(test_id(42),test_id(10),'ADMIN','#fff',50,'{"administrator":true}'),(test_id(43),test_id(10),'MOD','#fff',20,'{"manage_voice":true,"manage_roles":true}');
INSERT INTO member_roles VALUES(test_id(31),test_id(41)),(test_id(32),test_id(42)),(test_id(33),test_id(43));
